version: 2

run:
  timeout: 5m
  print-issued-lines: true
  print-linter-name: true
  concurrency: 4

linters:
  disable-all: true
  enable:
    - gocyclo
    - staticcheck
    - errcheck
    - govet
    - unused
    - bodyclose
    - noctx
    - asasalint
    #- revive
    #- gosec
    #- nilerr

linters-settings:
  gocyclo:
    min-complexity: 15