# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: mtracer

git:
  tag_sort: semver

before:
  hooks:
    - go mod tidy -diff
    - go mod download
    - go run main.go gendocs 

builds:
  - id: mtracer-darwin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mtracer-project/mtracer/cmd.Version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - id: mtracer-linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mtracer-project/mtracer/cmd.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: mtracer-windows
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mtracer-project/mtracer/cmd.Version={{.Version}}
    goos:
      - windows
    goarch:
      - amd64
      - arm64

gomod:
  proxy: false

archives:
  - id: mtracer-darwin
    ids:
      - mtracer-darwin
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - src: "man/*"
        dst: "man"

  - id: mtracer-linux
    ids:
      - mtracer-linux
    formats: [tar.zst]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - src: "man/*"
        dst: "man"

  - id: mtracer-windows
    ids:
      - mtracer-windows
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - src: "man/*"
        dst: "man"
report_sizes: true

# Homebrew configuration
homebrew_casks:
  - ids:
      - mtracer-darwin
    manpages:
      - man/*.1
      - "!man/*-completion*.1"

    generate_completions_from_executable:
      executable: "bin/mtracer"
      args:
        - completion
      shell_parameter_format: cobra
      shells:
        - bash
        - zsh
        - fish
        - pwsh
    url:
      # URL which is determined by the given Token (github, gitlab or gitea).
      template: "https://github.com/mtracer-project/mtracer/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      # Used when the domains of `url` and `homepage` differ.
      verified: "github.com/mtracer-project/mtracer"
      # Tool's website, will become github pages
      cookies:
        license: "accept-backup"
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/mtracer-project/mtracer
    caveats: "🚀 Let's trace!"
    description: >-
      {{ .ProjectName }} is a CLI tool designed to facilitate testing through trace validation with tracing functionalities on distributed systems, released in version {{ .Tag }}.
    skip_upload: auto
    # Repository to push the generated files to.
    repository:
      owner: mtracer-project
      name: homebrew-tap
      branch: main
      token: "{{ .Env.PKG_PUBLISHER_GITHUB_TOKEN }}"
    commit_author:
      name: mtracer-releaser
      email: alessandro.dinato@gmail.com

# Winget and Scoop configuration
winget:
  - name: mtracer
    ids:
      - mtracer-windows
    publisher: mtracer
    short_description: "CLI tool designed to facilitate testing through trace validation"
    license: "AGPL-3.0"
    publisher_url: https://github.com/mtracer-project
    package_identifier: mtracer.mtracer
    homepage: "https://mtracer-project.github.io"
    description: "mtracer is a CLI tool designed to facilitate testing through trace validation with tracing functionalities on distributed systems."
    tags:
      - golang
      - e2e
      - open-telemetry
      - otel
      - distributed-systems
      - cli
      - tracing
    repository:
      owner: mtracer-project
      name: winget-pkgs
      branch: mtracer-release-{{.Version}}
      token: "{{ .Env.PUBLIC_PKG_PUBLISHER_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
    commit_author:
      name: mtracer-releaser
      email: alessandro.dinato@gmail.com

scoops:
  - name: mtracer
    ids:
      - mtracer-windows
    description: "mtracer is a CLI tool designed to facilitate testing through trace validation."
    homepage: "https://mtracer-project.github.io"
    license: "AGPL-3.0"
    repository:
      owner: mtracer-project
      name: scoop-bucket
      branch: main
      token: "{{ .Env.PKG_PUBLISHER_GITHUB_TOKEN }}"
    commit_author:
      name: mtracer-releaser
      email: alessandro.dinato@gmail.com

release:
  github:
    owner: mtracer-project
    name: mtracer
  replace_existing_artifacts: true
  mode: replace

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--no-tty"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: desc
  filters:
    exclude: # exludes commits starting with "X:"
      - "^docs" # documentation
      - "^test" # tests
      - "^chore" # small fixes or changes
      - "^ci" # ci/cd
      - "^refactor" # refactoring
      - "^style" # code style
      - "^perf" # performance improvements
      - "^build" # build system changes
      - "^revert" # reverts