# GoReleaser configuration for Homebrew publishing
homebrew_casks:
  - ids:
      - mtrace-darwin
    manpages:
      - man/*.1
      - "!man/*-completion*.1"

    generate_completions_from_executable:
      executable: "bin/mtrace"
      args:
        - completions
      shell_parameter_format: cobra
      shells:
        - bash
        - zsh
        - fish
        - pwsh
    url:
      # URL which is determined by the given Token (github, gitlab or gitea).
      template: "https://github.com/mtrace-project/mtrace/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      # Used when the domains of `url` and `homepage` differ.
      verified: "github.com/mtrace-project/mtrace"
      # Tool's website, will become github pages
      cookies:
        license: "accept-backup"
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/mtrace-project/mtrace
    caveats: "🚀 Let's trace!"
    description: >-
      {{ .ProjectName }} is a CLI tool designed to facilitate testing through trace validation with tracing functionalities on distributed systems, released in version {{ .Tag }}.
    skip_upload: auto
    # Repository to push the generated files to.
    repository:
      owner: aledinato
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: aledinato
          name: homebrew-tap
          branch: main    
    commit_author:
      name: aledinato-bot
      email: alessandro.dinato@gmail.com
      signing:
        enabled: true
        key: "{{ .Env.GPG_SIGNING_KEY }}"
        program: gpg
        format: openpgp

