// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: trace/trace.proto

package trace

import (
	span "github.com/mtrace-project/mtrace/span"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	SpanCount     int32                  `protobuf:"varint,5,opt,name=span_count,json=spanCount,proto3" json:"span_count,omitempty"`
	ErrorCount    int32                  `protobuf:"varint,6,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	Spans         []*span.SpanProto      `protobuf:"bytes,7,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceProto) Reset() {
	*x = TraceProto{}
	mi := &file_trace_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceProto) ProtoMessage() {}

func (x *TraceProto) ProtoReflect() protoreflect.Message {
	mi := &file_trace_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceProto.ProtoReflect.Descriptor instead.
func (*TraceProto) Descriptor() ([]byte, []int) {
	return file_trace_trace_proto_rawDescGZIP(), []int{0}
}

func (x *TraceProto) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceProto) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TraceProto) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TraceProto) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *TraceProto) GetSpanCount() int32 {
	if x != nil {
		return x.SpanCount
	}
	return 0
}

func (x *TraceProto) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *TraceProto) GetSpans() []*span.SpanProto {
	if x != nil {
		return x.Spans
	}
	return nil
}

var File_trace_trace_proto protoreflect.FileDescriptor

const file_trace_trace_proto_rawDesc = "" +
	"\n" +
	"\x11trace/trace.proto\x12\fmtrace.trace\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x0fspan/span.proto\"\xbe\x02\n" +
	"\n" +
	"TraceProto\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x1d\n" +
	"\n" +
	"span_count\x18\x05 \x01(\x05R\tspanCount\x12\x1f\n" +
	"\verror_count\x18\x06 \x01(\x05R\n" +
	"errorCount\x12,\n" +
	"\x05spans\x18\a \x03(\v2\x16.mtrace.span.SpanProtoR\x05spansBDZBgithub.com/mtrace-project/mtrace/traceb\x06proto3"

var (
	file_trace_trace_proto_rawDescOnce sync.Once
	file_trace_trace_proto_rawDescData []byte
)

func file_trace_trace_proto_rawDescGZIP() []byte {
	file_trace_trace_proto_rawDescOnce.Do(func() {
		file_trace_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trace_trace_proto_rawDesc), len(file_trace_trace_proto_rawDesc)))
	})
	return file_trace_trace_proto_rawDescData
}

var file_trace_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_trace_trace_proto_goTypes = []any{
	(*TraceProto)(nil),            // 0: mtrace.trace.TraceProto
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 2: google.protobuf.Duration
	(*span.SpanProto)(nil),        // 3: mtrace.span.SpanProto
}
var file_trace_trace_proto_depIdxs = []int32{
	1, // 0: mtrace.trace.TraceProto.start_time:type_name -> google.protobuf.Timestamp
	1, // 1: mtrace.trace.TraceProto.end_time:type_name -> google.protobuf.Timestamp
	2, // 2: mtrace.trace.TraceProto.duration:type_name -> google.protobuf.Duration
	3, // 3: mtrace.trace.TraceProto.spans:type_name -> mtrace.span.SpanProto
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_trace_trace_proto_init() }
func file_trace_trace_proto_init() {
	if File_trace_trace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trace_trace_proto_rawDesc), len(file_trace_trace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trace_trace_proto_goTypes,
		DependencyIndexes: file_trace_trace_proto_depIdxs,
		MessageInfos:      file_trace_trace_proto_msgTypes,
	}.Build()
	File_trace_trace_proto = out.File
	file_trace_trace_proto_goTypes = nil
	file_trace_trace_proto_depIdxs = nil
}
