// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: span/span.proto

package span

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpanProto struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SpanId        string                     `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentId      string                     `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ServiceName   string                     `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName string                     `protobuf:"bytes,4,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	SpanKind      string                     `protobuf:"bytes,5,opt,name=span_kind,json=spanKind,proto3" json:"span_kind,omitempty"`
	SpanStatus    string                     `protobuf:"bytes,6,opt,name=span_status,json=spanStatus,proto3" json:"span_status,omitempty"`
	StartTime     *timestamppb.Timestamp     `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp     `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration      *durationpb.Duration       `protobuf:"bytes,9,opt,name=duration,proto3" json:"duration,omitempty"`
	Attributes    map[string]*structpb.Value `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanProto) Reset() {
	*x = SpanProto{}
	mi := &file_span_span_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanProto) ProtoMessage() {}

func (x *SpanProto) ProtoReflect() protoreflect.Message {
	mi := &file_span_span_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanProto.ProtoReflect.Descriptor instead.
func (*SpanProto) Descriptor() ([]byte, []int) {
	return file_span_span_proto_rawDescGZIP(), []int{0}
}

func (x *SpanProto) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *SpanProto) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *SpanProto) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SpanProto) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *SpanProto) GetSpanKind() string {
	if x != nil {
		return x.SpanKind
	}
	return ""
}

func (x *SpanProto) GetSpanStatus() string {
	if x != nil {
		return x.SpanStatus
	}
	return ""
}

func (x *SpanProto) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SpanProto) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SpanProto) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *SpanProto) GetAttributes() map[string]*structpb.Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_span_span_proto protoreflect.FileDescriptor

const file_span_span_proto_rawDesc = "" +
	"\n" +
	"\x0fspan/span.proto\x12\vmtrace.span\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x91\x04\n" +
	"\tSpanProto\x12\x17\n" +
	"\aspan_id\x18\x01 \x01(\tR\x06spanId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12%\n" +
	"\x0eoperation_name\x18\x04 \x01(\tR\roperationName\x12\x1b\n" +
	"\tspan_kind\x18\x05 \x01(\tR\bspanKind\x12\x1f\n" +
	"\vspan_status\x18\x06 \x01(\tR\n" +
	"spanStatus\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x125\n" +
	"\bduration\x18\t \x01(\v2\x19.google.protobuf.DurationR\bduration\x12F\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2&.mtrace.span.SpanProto.AttributesEntryR\n" +
	"attributes\x1aU\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01BCZAgithub.com/mtrace-project/mtrace/spanb\x06proto3"

var (
	file_span_span_proto_rawDescOnce sync.Once
	file_span_span_proto_rawDescData []byte
)

func file_span_span_proto_rawDescGZIP() []byte {
	file_span_span_proto_rawDescOnce.Do(func() {
		file_span_span_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_span_span_proto_rawDesc), len(file_span_span_proto_rawDesc)))
	})
	return file_span_span_proto_rawDescData
}

var file_span_span_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_span_span_proto_goTypes = []any{
	(*SpanProto)(nil),             // 0: mtrace.span.SpanProto
	nil,                           // 1: mtrace.span.SpanProto.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 3: google.protobuf.Duration
	(*structpb.Value)(nil),        // 4: google.protobuf.Value
}
var file_span_span_proto_depIdxs = []int32{
	2, // 0: mtrace.span.SpanProto.start_time:type_name -> google.protobuf.Timestamp
	2, // 1: mtrace.span.SpanProto.end_time:type_name -> google.protobuf.Timestamp
	3, // 2: mtrace.span.SpanProto.duration:type_name -> google.protobuf.Duration
	1, // 3: mtrace.span.SpanProto.attributes:type_name -> mtrace.span.SpanProto.AttributesEntry
	4, // 4: mtrace.span.SpanProto.AttributesEntry.value:type_name -> google.protobuf.Value
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_span_span_proto_init() }
func file_span_span_proto_init() {
	if File_span_span_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_span_span_proto_rawDesc), len(file_span_span_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_span_span_proto_goTypes,
		DependencyIndexes: file_span_span_proto_depIdxs,
		MessageInfos:      file_span_span_proto_msgTypes,
	}.Build()
	File_span_span_proto = out.File
	file_span_span_proto_goTypes = nil
	file_span_span_proto_depIdxs = nil
}
