name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GOPRIVATE: "github.com/*"

jobs:
  goreleaser-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
        
      - name: Verify tag is on main branch
        run: |
          git fetch origin main
          if ! git branch -r --contains ${{ github.ref_name }} | grep -E "(^|\s)origin/main$"; then
            echo "Error: Tag ${{ github.ref_name }} is not on the main branch."
            exit 1
          fi

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: mtrace_${{ github.ref_name }}_dist
          path: |
            dist/*.zip
            dist/*.tar.zst
            dist/*.tar
            dist/*.json
            dist/*.md
            dist/*.txt
            dist/*.sig
          retention-days: 56
